version: '3.9'

networks:
  ocabox-network:
    driver: bridge

services:
  ocabox:
    build:
      context: ./
      args:
        OCABOX_ROUTER_PORT: ${OCABOX_ROUTER_PORT}
    stop_signal: SIGINT
    ports:
      - ${OCABOX_ROUTER_PORT}:${OCABOX_ROUTER_PORT}
    volumes:
      - './obsrv/comunication/:/obsrv/comunication/'
    networks:
      - ocabox-server-network
