__author__ = " Ernest Lasek (elasek@akond.com), Mikołaj Kałuszyński (mkalusz@camk.edu.pl)"
__copyright__ = ""
__credits__ = ["Ernest Lasek (elasek@akond.com)", "Mikołaj Kałuszyński (mkalusz@camk.edu.pl)"]
__license__ = "MIT"
__version_num__ = [1, 0, 0]
__version__ = "{}.{}.{}".format(*__version_num__)
__maintainer__ = "Mikołaj Kałuszyński (mkalusz@camk.edu.pl)"
__email__ = "mkalusz@camk.edu.pl"
__status__ = "Development"
