settings:
  packet_size: 1024
  command_timeout: 5.0
  nats_url: "nats://127.0.0.1:4222"
  nats_subject: "svc.rpc.irsi" # Global topic

mappings:
  commands:
    camera:
      camerastate:
        command: "sync"
    filterwheel:
      position:
        command: "filter"
        get_arg: "status"        
    nats:
      ccdtemperature:
        key: "temperature"
        subject: "svc.rpc.iris.camera.ccdtemperature"

  actions:
    startexposure:
      - command: "et"
        value: "{Duration}"
      - command: "go"
        value: null
    stopexposure:
      - command: "clear"
        value: null
    startdownload:
      - command: "xfer"
        value: "{filename}"